name: Deploy SpaceHive360 Backend

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Create folder if not exists
            mkdir -p /app/spacehive

            # Create .env file
            echo "PostgreConnection=${{ secrets.POSTGRES_CONNECTION }}" > /app/spacehive/.env
            echo "ASPNETCORE_ENVIRONMENT=Production" >> /app/spacehive/.env
            echo "JwtSettings__Secret=${{ secrets.JWT_SECRET }}" >> /app/spacehive/.env
            echo "JwtSettings__Issuer=${{ secrets.JWT_ISSUER }}" >> /app/spacehive/.env
            echo "JwtSettings__Audience=${{ secrets.JWT_AUDIENCE }}" >> /app/spacehive/.env
            echo "JwtSettings__ExpiryMinutes=60" >> /app/spacehive/.env

            # Pull latest code
            cd /app/spacehive
            git config --global --add safe.directory /app/spacehive
            git pull origin develop

            # Restart Docker
            docker-compose down
            docker-compose up -d --build